# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Эл. адрес')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
