# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('short_description', models.TextField(blank=True, default=None, max_length=256, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='books_images/')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
                ('tags', models.ManyToManyField(related_name='tags', related_query_name='tags', to='tags.Tag')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'книги',
            },
        ),
    ]
